server:
    port: ${APPLICATION_PORT:8080}

spring:
    servlet:
        multipart:
            maxFileSize: 10MB
            maxRequestSize: 10MB
    application:
        name: fileserver
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:fileserver}
        username: ${POSTGRES_USER:admin}
        password: ${POSTGRES_PASSWORD:admin}

storage:
    location: storage
